version: "3.9"

services:
  bridge:
    image: ubuntu:22.04
    container_name: matter-bridge
    network_mode: host
    privileged: true
    environment:
      - CLOUD_BASE_URL=http://127.0.0.1:6000
    volumes:
      - /home/ucd/smarthome/bridgeMatter:/opt/bridgeMatter:rw
    working_dir: /opt/bridgeMatter/bridge-app/linux
    command: >
      bash -lc "set -e;
        apt-get update;
        DEBIAN_FRONTEND=noninteractive apt-get install -y git pkg-config ninja-build
        gcc g++ python3 python3-venv python3-dev libssl-dev libdbus-1-dev
        libglib2.0-dev unzip curl ca-certificates;
        source /opt/bridgeMatter/script/activate.sh;
        gn gen out/debug;
        ninja -C out/debug;
        ./out/debug/chip-bridge-app"
